sudo: required

services:
- docker

env:
  global:
    - CURRENT_GIT_BRANCH=$TRAVIS_BRANCH
    - DOCKER_COMPOSE_VERSION=1.18.0
    - DOCKER_COMPOSE_BIN=/usr/local/bin/docker-compose

before_install:
  - sudo rm -f "${DOCKER_COMPOSE_BIN}"
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-"$(uname -s)"-"$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose "${DOCKER_COMPOSE_BIN}"
  docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

script:
- make docker

# Do not deploy if Pull Request
# If a contributor want to deploy on its own DockerHub account:
# 1 - Enable Travis on the forked repository
# 2 - Set the environment variable DOCKERHUB_USERNAME in Travis Settings
deploy:
- provider: script
  script: make docker-deploy
  on:
    condition: $TRAVIS_BRANCH = master
