version: '3'

networks:
  admin:
    driver: overlay
  front:
    driver: overlay

services:
  registry:
    image: registry:2
    deploy:
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    networks:
    - front
    ports:
    - "5001:5000"

  lb:
    image: traefik
    deploy:
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    networks:
    - front
    command: --docker --docker.swarmmode --docker.domain=${EXTERNAL_DOMAIN} --docker.watch --web
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "10000:80"
    - "8081:8080"

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    networks:
    - admin
    ports:
    - "8080:8080"
    environment:
    - HOST=${EXTERNAL_DOMAIN}
    - PORT=8080
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
