version: '3'

networks:
  default:
    driver:
      bridge
  front:
    driver:
      bridge

services:
  front:
    restart: unless-stopped
    build: ./front/
    read_only: true
    ports:
    - "10000:10000"

  gitserver:
    restart: unless-stopped
    build:
      context: ./gitserver/
      args:
      - FIRST_USER=butler

  jenkins:
    restart: unless-stopped
    build: ./jenkins/
    read_only: true

  docker-agent:
    restart: unless-stopped
    build: ./jenkins-agent/
    read_only: true

  maven-agent:
    restart: unless-stopped
    build: ./jenkins-agent/
    read_only: true

  devbox:
    restart: unless-stopped
    build: ./devbox/
    read_only: true
    ports:
    - "10080:8080"

  registry:
    restart: unless-stopped
    read_only: true
    ports:
    - "5000:5000"

  docker-service:
    restart: unless-stopped
    read_only: true
