version: '3'

networks:
  default:
    driver: bridge

services:
  front:
    restart: on-failure
    container_name: front
    read_only: true
    environment:
    - EXTERNAL_DOMAIN=localhost

  gitserver:
    restart: on-failure
    container_name: gitserver
    environment:
    - EXTERNAL_DOMAIN=localhost
    - EXTERNAL_URL=http://git.localhost:${EXTERNAL_PORT}/gitserver

  jenkins:
    restart: on-failure
    read_only: true
    environment:
    - EXTERNAL_DOMAIN=localhost

  docker-agent:
    restart: on-failure
    read_only: true

  maven-agent:
    restart: on-failure
    read_only: true

  devbox:
    restart: on-failure
    read_only: true

  registry:
    restart: on-failure
    read_only: true

  docker-service:
    restart: on-failure
    read_only: true
