version: '3'

networks:
  default:
    driver: bridge

services:
  front:
    restart: unless-stopped
    build: ./front/
    container_name: front
    read_only: true
    environment:
    - EXTERNAL_DOMAIN=localhost

  gitserver:
    restart: unless-stopped
    container_name: gitserver
    build:
      context: ./gitserver/
      args:
      - FIRST_USER=butler
    environment:
    - EXTERNAL_DOMAIN=localhost
    - EXTERNAL_URL=http://git.localhost:${EXTERNAL_PORT}/gitserver

  jenkins:
    restart: unless-stopped
    build: ./jenkins/
    read_only: true
    environment:
    - EXTERNAL_DOMAIN=localhost

  docker-agent:
    restart: unless-stopped
    build: ./jenkins-agent/
    read_only: true

  maven-agent:
    restart: unless-stopped
    build: ./jenkins-agent/
    read_only: true

  devbox:
    restart: unless-stopped
    build: ./devbox/
    read_only: true

  registry:
    restart: unless-stopped
    read_only: true

  docker-service:
    restart: unless-stopped
    read_only: true
