version: '2.1'

volumes:
  docker-agent-data:
  maven-agent-data:
  jenkins-data:

services:

  front:
    build: ./front/
    container_name: front
    restart: unless-stopped
    depends_on:
    - gitserver
    - jenkins
    - devbox
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,size=10m
    - /var/cache/nginx:rw,noexec,size=10m
    - /var/run:rw,noexec,size=100k
    ports:
    - "10000:10000"
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_PORT=${EXTERNAL_PORT}

  gitserver:
    build:
      context: ./gitserver/
      args:
      - FIRST_USER=butler
    container_name: gitserver
    restart: unless-stopped
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - EXTERNAL_URL=http://git.${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/gitserver

  jenkins:
    build: ./jenkins/
    container_name: jenkins
    restart: unless-stopped
    environment:
    - JAVA_OPTS=-Xms1024m -Xmx1024m -Djenkins.install.runSetupWizard=false
    read_only: true
    volumes:
    - jenkins-data:/var/jenkins_home
    tmpfs:
    - /tmp:rw,exec,size=10m
    - /var/jenkins_home/war:rw,exec,size=100m
    - /var/jenkins_home/plugins:rw,exec,size=250m
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_OPTS=--prefix=/jenkins
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_PORT=${EXTERNAL_PORT}

  docker-agent:
    build: ./jenkins-agent/
    container_name: docker-agent
    restart: unless-stopped
    entrypoint: /sbin/tini -- /usr/local/bin/entrypoint.sh
    read_only: true
    volumes:
    - docker-agent-data:/home/jenkins
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc
    tmpfs:
    - /tmp:rw,exec,size=10m
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  maven-agent:
    build: ./jenkins-agent/
    container_name: maven-agent
    restart: unless-stopped
    read_only: true
    volumes:
    - maven-agent-data:/home/jenkins
    - /etc/ssh
    tmpfs:
    - /tmp:rw,exec,size=10m
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  devbox:
    build: ./devbox/
    restart: unless-stopped
    container_name: devbox
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,size=10m
    environment:
    - DOCKER_HOST=tcp://docker-service:2375
    ports:
    - "10080:8080"
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    read_only: true
    ports:
    - "5000:5000"

  docker-service:
    image: verb/socat:alpine
    container_name: docker-service
    restart: unless-stopped
    read_only: true
    command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
    ports:
    - "2375:2375"
    volumes:
    - /var/run/docker.sock:/docker.sock
