version: '3.4'

networks:
  default:
    driver:
      bridge
  front:
    driver:
      bridge

services:
  front:
    restart: unless-stopped
    build: ./front/
    read_only: true
    ports:
    - "10000:10000"

  gitserver:
    restart: unless-stopped
    build:
      context: ./gitserver/
      args:
      - first_user=butler
      - source_repo_to_mirror=https://github.com/oufti-playground/demoapp|demoapp

  jenkins:
    restart: unless-stopped
    build: ./jenkins/
    read_only: true

  docker-agent:
    restart: unless-stopped
    build:
      context: ./jenkins-agent/
      args:
      - CUSTOM_JVM_OPTS=${CUSTOM_JVM_OPTS}
    read_only: true

  maven-agent:
    restart: unless-stopped
    build:
      context: ./jenkins-agent/
      args:
      - CUSTOM_JVM_OPTS=${CUSTOM_JVM_OPTS}
    read_only: true

  devbox:
    restart: unless-stopped
    build:
      context: ./devbox/
      args:
      - CUSTOM_JVM_OPTS=${CUSTOM_JVM_OPTS}
    read_only: true
    ports:
    - "10080:8080"

  registry:
    image: registry:2
    restart: unless-stopped
    read_only: true
    ports:
    - "5000:5000"

  docker-service:
    restart: unless-stopped
    read_only: true
