version: '3'

networks:
  default:
    driver: overlay

# TMPFS Volumes from https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options
volumes:
  nginx-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  nginx-cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  nginx-run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=100k
  jenkins-data:
    driver: local
  jenkins-war:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=100m
  jenkins-plugins:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=250m
  devbox-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  docker-agent-data:
    driver: local
  maven-agent-data:
    driver: local

services:

  front:
    build: ./front/
    image: front
    depends_on:
    - jenkins
    - gitserver
    - devbox
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      placement:
        constraints:
          - node.hostname == worker2
    volumes:
    - nginx-tmp:/tmp
    - nginx-cache:/var/cache/nginx
    - nginx-run:/var/run
    ports:
    - "10000:10000"
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    env_file: .env

  gitserver:
    build:
      context: ./gitserver/
      args:
      - FIRST_USER=butler
    image: gitserver
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    env_file: .env
    environment:
    - EXTERNAL_URL=http://git.${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/gitserver

  jenkins:
    build: ./jenkins/
    image: jenkins
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    volumes:
    - jenkins-data:/var/jenkins_home
    - /tmp
    - jenkins-war:/var/jenkins_home/war
    - jenkins-plugins:/var/jenkins_home/plugins
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_OPTS=--prefix=/jenkins
    - JAVA_OPTS=-Xms1024m -Xmx1024m -Djenkins.install.runSetupWizard=false
    env_file: .env

  docker-agent:
    build: ./jenkins-agent/
    image: docker-agent
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    volumes:
    - docker-agent-data:/home/jenkins
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  maven-agent:
    build: ./jenkins-agent/
    image: maven-agent
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    volumes:
    - maven-agent-data:/home/jenkins
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  devbox:
    build: ./devbox/
    image: devbox
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      placement:
        constraints:
          - node.hostname == worker2
    volumes:
    - devbox-tmp:/tmp
    environment:
    - DOCKER_HOST=tcp://docker-service:2375
    ports:
    - "10080:8080"
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    - "git.${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"

  registry:
    image: registry:2
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    ports:
    - "5000:5000"

  docker-service:
    image: verb/socat:alpine
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
    command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
    ports:
    - "2375:2375"
    volumes:
    - /var/run/docker.sock:/docker.sock
