version: '2.1'

volumes:
  docker-agent-data:
  maven-agent-data:

services:

  front:
    build: ./front/
    container_name: front
    restart: unless-stopped
    depends_on:
    - gitserver
    - jenkins
    - devbox
    network_mode: "host"
    extra_hosts:
    - "devbox:${DOCKER_BRIDGE_IP}"
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_PORT=${EXTERNAL_PORT}

  gitserver:
    build:
      context: ./gitserver/
      args:
      - FIRST_USER=butler
    container_name: gitserver
    restart: unless-stopped
    network_mode: "host"
    environment:
    - EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/gitserver

  jenkins:
    build: ./jenkins/
    container_name: jenkins
    restart: unless-stopped
    network_mode: "host"
    extra_hosts:
    - "docker-agent:${DOCKER_BRIDGE_IP}"
    - "maven-agent:${DOCKER_BRIDGE_IP}"
    - "moby:${DOCKER_BRIDGE_IP}"
    - "alpine35:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_OPTS=--prefix=/jenkins
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_PORT=${EXTERNAL_PORT}

  docker-agent:
    build: ./docker-agent/
    container_name: docker-agent
    restart: unless-stopped
    volumes:
    - docker-agent-data:/home/jenkins
    - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    ports:
    - "4022:22"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  maven-agent:
    build: ./maven-agent/
    container_name: maven-agent
    restart: unless-stopped
    volumes:
    - maven-agent-data:/home/jenkins
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}" # For getting git repo
    ports:
    - "5022:22"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  devbox:
    build: ./devbox/
    restart: unless-stopped
    container_name: devbox
    environment:
    - DOCKER_HOST=tcp://docker-service:2375
    ports:
    - "7681:7681"
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
    - "5000:5000"

  docker-service:
    image: verb/socat:alpine
    container_name: docker-service
    restart: unless-stopped
    command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
    ports:
    - "2375:2375" # Serve Docker requests externaly
    volumes:
    - /var/run/docker.sock:/docker.sock
