version: '3'

networks:
  default:
    driver:
      overlay
  front:
    external:
      name: admin_front

# TMPFS Volumes from https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options
volumes:
  nginx-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  nginx-cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  nginx-run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=100k
  jenkins-data:
    driver: local
  jenkins-war:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=100m
  jenkins-plugins:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=250m
  devbox-tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: rw,noexec,size=10m
  docker-agent-data:
    driver: local
  maven-agent-data:
    driver: local

services:
  front:
    image: ${REGISTRY_URL}/front
    depends_on:
    - jenkins
    - gitserver
    - devbox
    labels:
    - "traefik.port=10000"
    - "traefik.frontend.rule=Host:${EXTERNAL_DOMAIN}"
    - "traefik.docker.network=admin_front"
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 6
        window: 5s
      labels:
      - "traefik.port=10000"
      - "traefik.frontend.rule=Host:${EXTERNAL_DOMAIN}"
      - "traefik.docker.network=admin_front"
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 16M
    networks:
    - default
    - front
    volumes:
    - nginx-tmp:/tmp
    - nginx-cache:/var/cache/nginx
    - nginx-run:/var/run
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    env_file: .env
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - REGISTRY_URL=${REGISTRY_URL}
    - REGISTRY_USER=${COMPOSE_PROJECT_NAME:-registry_user}

  gitserver:
    image: ${REGISTRY_URL}/gitserver
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    env_file: .env
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - EXTERNAL_URL=http://${EXTERNAL_DOMAIN}:${EXTERNAL_PORT}/gitserver

  jenkins:
    image: ${REGISTRY_URL}/jenkins
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      resources:
        limits:
          memory: 2560M
        reservations:
          memory: 1536M
    volumes:
    - jenkins-data:/var/jenkins_home
    - /tmp
    - jenkins-war:/var/jenkins_home/war
    - jenkins-plugins:/var/jenkins_home/plugins
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    - JENKINS_OPTS=--prefix=/jenkins
    env_file: .env

  docker-agent:
    image: ${REGISTRY_URL}/docker-agent
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    volumes:
    - docker-agent-data:/home/jenkins
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  maven-agent:
    image: ${REGISTRY_URL}/maven-agent
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 384M
    volumes:
    - maven-agent-data:/home/jenkins
    - /etc
    - /tmp
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"
    environment:
    - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

  devbox:
    image: ${REGISTRY_URL}/devbox
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 384M
    volumes:
    - devbox-tmp:/tmp
    environment:
    - DOCKER_HOST=tcp://docker-service:2375
    extra_hosts:
    - "${EXTERNAL_DOMAIN}:${DOCKER_BRIDGE_IP}"

  docker-service:
    image: verb/socat:alpine
    deploy:
      placement:
        constraints:
        - node.role != manager
        - engine.labels.family == app
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 2s
      resources:
        limits:
          memory: 16M
        reservations:
          memory: 8M
    command: tcp-listen:2375,reuseaddr,fork unix:/docker.sock
    volumes:
    - /var/run/docker.sock:/docker.sock
